# coding: utf-8

"""
    Reseller API

    API allowing resellers to create and manage contracts 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_reseller_api_v2_client.models.pagination_links import PaginationLinks

class TestPaginationLinks(unittest.TestCase):
    """PaginationLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationLinks:
        """Test PaginationLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationLinks`
        """
        model = PaginationLinks()
        if include_optional:
            return PaginationLinks(
                prev = '<PREVIOUS-PAGE-URI>',
                var_self = '<THIS-PAGE-URI>',
                next = '<NEXT-PAGE-URI>'
            )
        else:
            return PaginationLinks(
        )
        """

    def testPaginationLinks(self):
        """Test PaginationLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
