# coding: utf-8

"""
    Reseller API

    API allowing resellers to create and manage contracts 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_reseller_api_v2_client.contract_api import ContractApi


class TestContractApi(unittest.TestCase):
    """ContractApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractApi()

    def tearDown(self) -> None:
        pass

    def test_create_contract(self) -> None:
        """Test case for create_contract

        Create new contract
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Get all contracts
        """
        pass

    def test_find_by_id(self) -> None:
        """Test case for find_by_id

        Find contract by ID
        """
        pass

    def test_update_contract(self) -> None:
        """Test case for update_contract

        Update contract
        """
        pass

    def test_update_contract_resource_limits(self) -> None:
        """Test case for update_contract_resource_limits

        Update resource limits for contract
        """
        pass

    def test_update_name(self) -> None:
        """Test case for update_name

        Update contract name
        """
        pass


if __name__ == '__main__':
    unittest.main()
