# coding: utf-8

"""
    Reseller API

    API allowing resellers to create and manage contracts 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ionos_reseller_api_v2_client.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_create_admin(self) -> None:
        """Test case for create_admin

        Create new admin user for contract
        """
        pass

    def test_delete_admin(self) -> None:
        """Test case for delete_admin

        Delete admin user
        """
        pass

    def test_find_admin_by_id(self) -> None:
        """Test case for find_admin_by_id

        Find admin by ID
        """
        pass

    def test_find_all_admins(self) -> None:
        """Test case for find_all_admins

        Get all admin users of the contract
        """
        pass

    def test_update_admin(self) -> None:
        """Test case for update_admin

        Partially update admin user
        """
        pass


if __name__ == '__main__':
    unittest.main()
